import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Particles from "@/components/common/particle-background";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        {children}
        <Particles
          className="absolute -z-50 inset-0 w-full h-full"
          quantity={500}
          ease={80}
          color="#000"
          refresh
        />
        <Toaster />
      </body>
    </html>
  );
}
